// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpzESQLJBTJBsAp6LenM0pFQQLrAsCivQ',
    appId: '1:599849169513:web:f8716a4a2581072a8468f8',
    messagingSenderId: '599849169513',
    projectId: 'sda-youth-app',
    authDomain: 'sda-youth-app.firebaseapp.com',
    storageBucket: 'sda-youth-app.firebasestorage.app',
    measurementId: 'G-NDN2F9649S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbwibfh6eaLNMe8X5JYItk7-DZpOi14o',
    appId: '1:599849169513:android:db6c3945c0ae48a48468f8',
    messagingSenderId: '599849169513',
    projectId: 'sda-youth-app',
    storageBucket: 'sda-youth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfO0-7FMuIyCpuvwV5vFAoCk5J6LvbCJE',
    appId: '1:599849169513:ios:e5b1e6f4f7a8f7e18468f8',
    messagingSenderId: '599849169513',
    projectId: 'sda-youth-app',
    storageBucket: 'sda-youth-app.firebasestorage.app',
    iosClientId: '599849169513-ao90da047nvj1odrhojs6kbqcrcknfb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdaYouthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfO0-7FMuIyCpuvwV5vFAoCk5J6LvbCJE',
    appId: '1:599849169513:ios:e5b1e6f4f7a8f7e18468f8',
    messagingSenderId: '599849169513',
    projectId: 'sda-youth-app',
    storageBucket: 'sda-youth-app.firebasestorage.app',
    iosClientId: '599849169513-ao90da047nvj1odrhojs6kbqcrcknfb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdaYouthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpzESQLJBTJBsAp6LenM0pFQQLrAsCivQ',
    appId: '1:599849169513:web:c9afb0c0037f74b68468f8',
    messagingSenderId: '599849169513',
    projectId: 'sda-youth-app',
    authDomain: 'sda-youth-app.firebaseapp.com',
    storageBucket: 'sda-youth-app.firebasestorage.app',
    measurementId: 'G-QVRPRSEVM2',
  );

}